version: '3.7'
services:
  app-server:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
